# Site settings
title: Andrii Degeler # site title
description: >- # site description
  Homepage
lang: en-US # default lang
timezone: Europe/Amsterdam # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/shlema/shlema.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# telegram comments
telegram_site_id: "Sc-g4c-R"

# Profile settings
author:
  name: Andrii Degeler # author name
  bio: >- # tell to the world
    Podcast host and producer, tech journalist
  username: shlema # general username
  github: shlema # github username
  twitter: adegeler # twitter username
  facebook: shlema # facebook username
  linkedin: shlema
  instagram: adegeler
  email: shlema@gmail.com # email adress
  avatar: /assets/img/adegeler-square-300.jpg # change with your own avatar

# URL settings
url: "https://shlema.me" #
baseurl:
permalink: /:title/
google_analytics: UA-41494970-1 # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
